### ISSUE TITLE
Função Rand()

### ISSUE THREAD

**Issue by alexsaiid** [robsonvleite/datalayer#10]
Bom dia Robson, 
Em primeiro lugar, parabéns pelo projeto, de fato é top.

Em segundo, rs..
Existe alguma forma de trabalhar com Rand() ?

Ex.

> 
> > use Example\Models\User;
> > $model = new User();
> > $count = $model->find()->count();
> > $users = $model->rand("0","$count " )->find()->limit(2)->fetch(true);

**Porque? uma forma de selecionar registros aleatórios de um bando, ferramenta muito usada para alimentar paginas de blog por exemplo**

**Comment by robsonvleite** [comment]
Tem sim,

```php
$users = $model->find()->order("RAND()")->fetch(true);
```
