### ISSUE TITLE
LOGIN SOCIAL COM GOOGLE E FACEBOOK CÓDIGO ABERTO T1

### ISSUE THREAD

**Issue by paulo-correia** [robsonvleite/datalayer#12]
Robson, 
Tem como disponibilizar todos os fontes?
Fiz tudo, mas o e-mail não enviou, não está salvando o "forget" no banco de dados, ao tentar se cadastrar sem ter conta via Facebook ou Google está apresentando "o e-mail informado já está em uso".
Se tiver os fontes consigo comparar melhor onde errei.

E se tiver dicas para quem usa VsCode no lugar do PhpStorm, tipo que extensões instalar para que fique tão simples quanto o PhpStorm agradeço ;)

**Comment by robsonvleite** [comment]
Sobre o componente PLZ;

**Comment by paulo-correia** [comment]
Robson,

Não entendi, explique melhor
