### ISSUE TITLE
Find method doesn't work with special character

### ISSUE THREAD

**Issue by PeterJason** [robsonvleite/datalayer#13]
Hi

Find method doesn't work correctly, you can see example code below.

`return (new self)->find("name=:name", "name=IT & Software")->fetch();`

How you know, you are using `parse_str` function...this is the problem.

**Comment by robsonvleite** [comment]
As an alternative to the occurrence of a character, you can run without preparation with due treatment.

```php
$bus->find("name = 'IT & Software'")->fetch();
```

**Comment by robsonvleite** [comment]
Example with statments

```php
$params = http_build_query(["name" => "UpInside & Associated"]);
$company = (new Company())->find("name = :name", $params);
var_dump($company, $company->fetch());
```

OK?
