### ISSUE TITLE
Paginação 

### ISSUE THREAD

**Issue by douglas-88** [robsonvleite/datalayer#15]
Boa tarde @robsonvleite , tudo bem ?
Primeiramente obrigado por seus conteúdos de PHP na Upinside, seus conteúdos sempre abordando o PHP na essência. 

Há como me tirar uma dúvida ?
De que forma poderia implementar uma paginação com filtros de busca,limitação de links e tals..., usando o seu componente, o DataLayer ?

Desde já agradeço a sua atenção.

**Comment by rodineiti** [comment]
> Boa tarde @robsonvleite , tudo bem ?
> Primeiramente obrigado por seus conteúdos de PHP na Upinside, seus conteúdos sempre abordando o PHP na essência.
> 
> Há como me tirar uma dúvida ?
> De que forma poderia implementar uma paginação com filtros de busca,limitação de links e tals..., usando o seu componente, o DataLayer ?
> 
> Desde já agradeço a sua atenção.

https://packagist.org/packages/coffeecode/paginator

**Comment by robsonvleite** [comment]
> > Boa tarde @robsonvleite , tudo bem ?
> > Primeiramente obrigado por seus conteúdos de PHP na Upinside, seus conteúdos sempre abordando o PHP na essência.
> > Há como me tirar uma dúvida ?
> > De que forma poderia implementar uma paginação com filtros de busca,limitação de links e tals..., usando o seu componente, o DataLayer ?
> > Desde já agradeço a sua atenção.
> 
> https://packagist.org/packages/coffeecode/paginator

Isso :)
