### ISSUE TITLE
Função find DataLayer

### ISSUE THREAD

**Issue by thiagocmelo** [robsonvleite/datalayer#17]
Olá, primeiramente queria parabenizar pelo trabalho, os seus vídeos estão modificando a forma de eu me divertir com o PHP.

Eu tenho uma dúvida quanto a find() do Datalayer:
Como eu passo mais de um parametro de filtro no find()?
$user = $model->**find("first_name = :name", "name=Robson")**->fetch();

Obrigado.

**Comment by felipeabranches** [comment]
@thiagocmelo , o find usa a função nativa do PHP `parse_str`
Seguindo a documentação, o correto seria fazer dessa forma
$user = $model->find("first_name = :name AND last_name = :last", "name=Robson&last=Leite")->fetch();

**Comment by vttsouza** [comment]
Olá a todos! Realmente os vídeos do @robsonvleite estão absurdamente cheios de valor!

Tenho uma dúvida também com relação ao undo do find(). No meu caso, não estou conseguindo usar a consulta com um LIKE.

$list = $users->find("usuario LIKE %:u%", ":u=admi")->fetch(true);

Tentei de alguma maneiras, porém, sem sucesso!

Grato a quem puder me ajudar!

**Comment by walissonhms** [comment]
Boa tarde amigo.

Para realizar a pesquisa com o find() basta seguir desta forma:

`$list = $users->find("usuario LIKE :u", ":u=%admi%")->fetch(true);`

**Comment by walissonhms** [comment]
> Olá a todos! Realmente os vídeos do @robsonvleite estão absurdamente cheios de valor!
> 
> Tenho uma dúvida também com relação ao undo do find(). No meu caso, não estou conseguindo usar a consulta com um LIKE.
> 
> $list = $users->find("usuario LIKE %:u%", ":u=admi")->fetch(true);
> 
> Tentei de alguma maneiras, porém, sem sucesso!
> 
> Grato a quem puder me ajudar!

Boa tarde amigo.

Para realizar a pesquisa com o `find()` basta seguir desta forma:

`$list = $users->find("usuario LIKE :u", ":u=%admi%")->fetch(true);`

**Comment by vttsouza** [comment]
Boa noite @walissonhms muito obrigado pela dica, contudo, olha como estava fazendo:

`$list = $users->find("usuario LIKE :us)", ":us=%adm%")->fetch(true);`

Isso estava gerando o seguinte erro:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

Achei estranho, então debuguei a minha variável `$users` e ela apresentava o seguinte na parte dos parâmetros:

`[params:protected] => Array
        (
            [:us] => �m% //Com esse caracter doido mesmo
        )
`
Pesquisando mais a fundo, agora a tarde percebi que era um probleminha proveniente de conversões de caracteres ou algo do tipo e encontrei uma forma que resolveu pra mim.

Inclusive vi sua resposta, agora, que entrei aqui para compartilhar a resolução do meu problema, pois, talvez possa ajudar mais alguém futuramente.

Meu código ficou da seguinte forma:

`$list = $users->find("usuario LIKE CONCAT('%',:us,'%')", ":us=adm")->fetch(true);`

E dessa forma, concatenando os percentuais direto com a instrução SQL, meu problema foi totalmente resolvido.

Outras informações do meu banco:
Default collation: latin1_swedish_ci
Default characterset: latin1

Talvez a collation não esteja correta, mas confesso, nunca ter parado para estudar um pouco mais essa questão da qual collation usar de fato.

Muito obrigado pela ajuda!

**Comment by walissonhms** [comment]
> Boa noite @walissonhms muito obrigado pela dica, contudo, olha como estava fazendo:
> 
> `$list = $users->find("usuario LIKE :us)", ":us=%adm%")->fetch(true);`
> 
> Isso estava gerando o seguinte erro:
> 
> > SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
> 
> Achei estranho, então debuguei a minha variável `$users` e ela apresentava o seguinte na parte dos parâmetros:
> 
> `[params:protected] => Array ( [:us] => �m% //Com esse caracter doido mesmo ) `
> 
> Pesquisando mais a fundo, agora a tarde percebi que era um probleminha proveniente de conversões de caracteres ou algo do tipo e encontrei uma forma que resolveu pra mim.
> 
> Inclusive vi sua resposta, agora, que entrei aqui para compartilhar a resolução do meu problema, pois, talvez possa ajudar mais alguém futuramente.
> 
> Meu código ficou da seguinte forma:
> 
> `$list = $users->find("usuario LIKE CONCAT('%',:us,'%')", ":us=adm")->fetch(true);`
> 
> E dessa forma, concatenando os percentuais direto com a instrução SQL, meu problema foi totalmente resolvido.
> 
> Outras informações do meu banco:
> Default collation: latin1_swedish_ci
> Default characterset: latin1
> 
> Talvez a collation não esteja correta, mas confesso, nunca ter parado para estudar um pouco mais essa questão da qual collation usar de fato.
> 
> Muito obrigado pela ajuda!

Opa, @vttsouza 

Desta forma também funciona:

`$list = $users->find(" usuario LIKE '%adm%' ")->fetch(true);`

**Comment by vttsouza** [comment]
Boa tarde, walissonhms.

Acredito que realmente o problema é o charset do meu banco então, porque, nem da forma que você comentou tinha dado certo também.

De qualquer forma, muito grato pela ajuda.

**Comment by robsonvleite** [comment]
Deve funcionar de ambas as formas:

```php
$users = (new User())->find("first_name LIKE :sfn", "sfn=%{$search}%")->fetch(true);
$users = (new User())->find("first_name LIKE '%' :sfn '%'", "sfn={$search}")->fetch(true);
```

O banco deve estar em utf8;
