### ISSUE TITLE
Método Destroy Não funciona

### ISSUE THREAD

**Issue by raoniokabayashirodrigues** [robsonvleite/datalayer#23]
Boa tarde!

Ao realizar o PHP Tips com tema - ABSTRAÇÃO DE BANCO DE DADOS COM DATA LAYER | PHP TIPS #002, tentei executar o método destroy(). Porém ele não funciona.

`<?php

require __DIR__ . "/../vendor/autoload.php";

use Source\Models\User;

$user = (new User())->findById(5);

$user->destroy();`

![image](https://user-images.githubusercontent.com/17757240/87080552-3861aa00-c1fe-11ea-95d1-249d14720fd7.png)

Podem me ajudar?

**Comment by raoniokabayashirodrigues** [comment]
Percebi que somente nomes que estão atrelados aos seus endereços pela FK, não podem serem excluídos. Como posso realizar a exclusão de maneira que reflita no banco de dados?


Schemas:

![image](https://user-images.githubusercontent.com/17757240/87155281-15cca100-c291-11ea-99f3-9148433ff3ae.png)

Table Address:

![image](https://user-images.githubusercontent.com/17757240/87155415-46143f80-c291-11ea-9736-264511080c40.png)

Table users:

![image](https://user-images.githubusercontent.com/17757240/87155434-52000180-c291-11ea-9467-caabbcd3938d.png)

**Comment by giovannialo** [comment]
Normalmente não é possível remover algum registro quando ele está atrelado a outro. Para isso, você precisa implementar a regra no seu banco de dados que, quando um usuário for deletado, o endereço deve ser deletado junto (efeito cascata).

**Comment by ThiagoOliveir4** [comment]
defina trigger para disparar após um registro for excluído, exemplo: destrói o id de maria através da id correto? Então você usa a trigger no banco de dados para fazer o feito em cascata, e todos os registros  que tiverem uma chave estrangeira de Maria também será excluído, essa função tá no banco de dados mesmo on cascade delete e update para atualizar  @giovannialo  & @raoniokabayashirodrigues

**Comment by vttsouza** [comment]
@raoniokabayashirodrigues bom dia.

Algo que você pode fazer é definir a regra de exclusão diretamente no banco, para manter a integridade do mesmo. Vou te mostrar um passo a passo, que talvez possa ajudar.

### Criando o banco

![01 - Create Database](https://user-images.githubusercontent.com/8833589/102476102-77135000-4039-11eb-8d03-8aae09c16a09.png)

`
CREATE DATABASE IF NOT EXISTS `exclusion_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
`

Aqui é a criação simples de um banco de teste usando UTF8.

 
 
### Criando a tabela Addresses

![02 - Create Table - Addresses](https://user-images.githubusercontent.com/8833589/102476282-b04bc000-4039-11eb-9e7b-18373953f3d7.png)

`
CREATE TABLE 'addresses' (
  'id' int(10) UNSIGNED NOT NULL,
  'street' varchar(255) NOT NULL,
  'number' varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

Aqui tudo normal também, apenas criei uma chave primária (id), um campo de rua (street) e um número (number).

 
 
### Criando a tabela Users

![03 - Create Table - Users](https://user-images.githubusercontent.com/8833589/102477663-6b288d80-403b-11eb-9a65-8340b0cb9fb0.png)

`
CREATE TABLE 'users' (
  'id' int(10) UNSIGNED NOT NULL,
  'address_id' int(10) UNSIGNED NOT NULL,
  'name' varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

Agora temos uma tabela simples também, com uma chave primária (id), uma chave estrangeira que no próximo passo vai referenciar o endereço (address_id) e um nome (name).

 
 
### Criando o relacionamento entre o User e o Address

![04 - Create Foreign Key](https://user-images.githubusercontent.com/8833589/102478428-55679800-403c-11eb-99cd-53a4b0b72ccc.png)

`
ALTER TABLE 'users'
  ADD CONSTRAINT 'fk_address_id' FOREIGN KEY ('address_id') REFERENCES 'addresses' ('id') ON DELETE CASCADE ON UPDATE NO ACTION;
`

Agora na tabela Users adicionamos uma chave estrangeira (foreign key) com o nome de fk_address_id, que receberá o id da tabela addresses.

A atenção aqui está na opção 'ON DELETE', que selecionei a opção 'CASCADE', ou seja, quando um endereço for excluído, o usuário ao qual esse endereço pertence, será excluído também, independente de estar sendo tratado ou não na aplicação.

A relação entre as tabelas ficou da seguinte forma:

![05 - Relation Tables](https://user-images.githubusercontent.com/8833589/102479281-77154f00-403d-11eb-8682-a6ca7923f9f3.png)

### Populando a tabela Addresses

![06 - Table Addresses](https://user-images.githubusercontent.com/8833589/102479398-9d3aef00-403d-11eb-8bc6-9c1fbd5e0043.png)

Criei dois endereços (id=1 e id=2).
 
 

### Populando a tabela Users

![07 - Table Users](https://user-images.githubusercontent.com/8833589/102479508-bf347180-403d-11eb-8e34-dac05ef54d67.png)

Criei três usuários, sendo que a Maria e o Marcos moram no mesmo endereço (address_id=2).
 
 
### Excluindo um endereço

![08 - Destroy Address (id=2)](https://user-images.githubusercontent.com/8833589/102480941-c0ff3480-403f-11eb-928e-3b8c761645fb.png)

Agora vou apagar diretamente no banco (tabela addresses), o endereço de id=2.
 
 
### Consultando a tabela Users

![09 - Result Reflected Users Table](https://user-images.githubusercontent.com/8833589/102481045-ef7d0f80-403f-11eb-8e8c-6072f5bc7834.png)

Podemos perceber agora, quando visualizamos o conteúdo da tabela users, que só existe o João.

Como o Marcos e a Maria possuíam o endereço id=2, e esse endereço foi  apagado e a tabela possui o parâmetro `ON DELETE CASCADE`, isso faz com que automaticamente o banco se encarregue de eliminar esses usuários.

### Considerações

Vale ressaltar que essa opção deve ser usada com cautela, pois, deve se adequar a sua regra de negócio.

Espero ter ajudado!
