### ISSUE TITLE
Erro ao tentar acessar propriedado do objeto quando a mesma não é do tipo STRING e possui um relacionamento de Tabelas acoplado

### ISSUE THREAD

**Issue by phsantosti** [robsonvleite/datalayer#24]
@robsonvleite 

Atualizei o componente DataLayer  para a versão  **_1.1.7 ou 1.1.5_** e estou tendo problemas ao acessar uma propriedade do objeto quando não for uma string e possui um relacionamento de tabela acoplado.

RELACIONAMENTO DE LEVEL COM USER

**`/**
     * @return DataLayer
     */
    public function level(): DataLayer
    {
        return (new LevelModel())->findById($this->level);
    }`**

Ao tentar acessar **`$this->level`** ou até mesmo depois de instanciar um novo **`$user = (new UserModel())->findById(1);`**

Quando acessso:

**`$this->level`** recebo erro.

Um simples find. 

**`: Notice: Undefined property: Application\Models\User\UserModel::$level in C:\xampp\htdocs\corecms\application\Models\User\UserModel.php `**

**Comment by robsonvleite** [comment]
Tente assim:

$user = (new UserModel())->findById(1);
echo $user->level;
