### ISSUE TITLE
Erro ao salvar (save()) no Coffecode DataLayer

### ISSUE THREAD

**Issue by vazjunior** [robsonvleite/datalayer#25]
Em ambiente localhost (desenvolvimento) não apresenta o erro mas ao hospedar no servidor (Hostgator) quando vou dar um save() apresenta o erro descrito:
Versão do DataLayer: 1.1.7
Versão do PHP: 7.4

![image](https://user-images.githubusercontent.com/69298375/89507678-d794a580-d79a-11ea-8fbc-d7645d0e0884.png)

**Comment by giovannialo** [comment]
Ressucitando =x

Provavelmente a sua consulta está retornando null e vc não fez um teste pra validar a existencia de dados para utilizá-los.
