### ISSUE TITLE
Datalayer em tabela com duas chaves primárias

### ISSUE THREAD

**Issue by Joinersa** [robsonvleite/datalayer#27]
Como usar o Datalayer em tabelas "do meio", ou seja, tabelas que possuem duas chaves estrangeiras, que são ao mesmo tempo chaves primárias composta?

No construtor de Datalayer é possível passar apenas uma chave primária, mas nesse caso são duas.

**Comment by giovannialo** [comment]
Não existe implementação para isso, atualmente. Eu tive o mesmo problema. O que você pode fazer é adicionar uma das chaves no parâmetro *primary* e a outra chave, adicionar no parâmetro *required*

**Comment by phsantosti** [comment]
ex: eu posso o seguinte cenário.
tabelas : 
levels: [id][name][status][created_at][updated_at]
permissions: [id][controller][method][description][status][created_at][updated_at]
levels_permissions: [id][level][permission][status][created_at][updated_at]
Tabela do meio acredito que seja esse seu caso: levels_permissions

Tenho um model chamado LevelPermissionModel
tem como primary o id dela normal e como required as chaves level e permission.

Dessa forma a minha tabela users possui chave estrangeira de levels e o levels possui x permissoes gracas ao relacionamento levels_permissions.
![image](https://user-images.githubusercontent.com/21990814/101243705-c1630b80-36e0-11eb-81a3-bd190712cb1d.png)
