### ISSUE TITLE
Proximo id da tabela 

### ISSUE THREAD

**Issue by cacio** [robsonvleite/datalayer#31]
Teria uma maneira de fazer pegar o próximo id antes de cadastrar , a select que usso pra isso sempre foi SHOW TABLE STATUS LIKE "tabela" teria uma forma de pegar por qui  $tab = (new tabela())->find("");

**Comment by vttsouza** [comment]
@cacio bom dia.

Acredito que uma maneira de pegar o próximo ID, seria pegar o último e adicionar + 1 a ele. Ficaria mais ou menos assim:

`
$lastID = ((new User())->find(null, null, "id")->order("id DESC")->fetch())->id;
`

Aqui estamos pegando apenas o último ID da tabela referenciado pelo Model User, agora basta incrementar 1 na variável e aplicar no que precisa.

Talvez tenha uma forma mais otimizada, então, se alguém puder compartilhar conosco, seria de grande valia a todos!

Espero que tenha ajudado.

Obrigado.

**Comment by giovannialo** [comment]
Ressucitando:::

Tenta

$lastId = (new User())->find('', '', 'MAX(id)')->fetch()->id;
