### ISSUE TITLE
Trabalhar com dois bancos

### ISSUE THREAD

**Issue by cacio** [robsonvleite/datalayer#34]
Teria uma maneira de trabalhar com dois bancos digamos eu tenho um MYSQL mas também tenho um banco local Firebird que preciso fazer fazer umas consultas teria uma maneira ali no DATA_LAYER_CONFIG configura uma maneira quando eu quero trabalhar com determinado banco na aquele momento ou com os dois , teria uma maneira dessa forma se tiver um exemplo agradeço obrigado

**Comment by giovannialo** [comment]
Com este componente, não. Um amigo meu, recentemente, teve essa necessidade tbm, mas por ele ser novo no dev, não conseguiu fazer. Eu fiz uma implementação utilizando este pacote pra ele onde, nas classes de modelo, é especificado o banco de dados que aquela classe iria usar.

Caso queira ver se te atende, é só executar a line command abaixo:

composer require stonks/datalayer

Fiz leves modificaçoes e adicionei outras coisinhas ao pacote que foram outras necessidades de outros brothers como utilizar funções sql na inserção/atualização de dados.

Abs.
