### ISSUE TITLE
Busca Equivalente ao LIKE '%aaaa%'

### ISSUE THREAD

**Issue by helisoncruz** [robsonvleite/datalayer#37]
Como ficaria usando essa classe uma busca do tipo LIKE usando o .find(), onde posso buscar apenas uma das parte do texto digitando? por exemplo, nome de um cliente.

`$customers = $model->find("cliente_nome = :name", "name=Nicolas Calebe da Mata")->fetch();`

Onde eu buscaria apenas Nicolas e me retornaria todos os Nicolas independente do sobrenome.

**Comment by euThiagoOliveira** [comment]
use http_build_query e passe os parâmetros deve resolver

**Comment by walissonhms** [comment]
Opa @helisoncruz blz?

Você pode tentar assim: 

`$customers = $model->find("cliente_nome LIKE '%Nicolas%'")->fetch(true);`

**Comment by helisoncruz** [comment]
Depois de testar bastante, eu busquei referencia na documentação do PDO e a forma que deu certo foi:

`$customers = $model->find("cliente_nome LIKE :name", "name=%{$search}%")->fetch(true);`

**Comment by omnispecies** [comment]
@helisoncruz e @walissonhms 
Podem abrir um pull request para acrescentar isso na documentação?
