### ISSUE TITLE
Problema ao atualizar valor booleano 

### ISSUE THREAD

**Issue by borges-cincatarina** [robsonvleite/datalayer#38]
Olá, estou enfrentando o seguinte problema quando tento salvar um valor do tipo boolean no banco.
![image](https://user-images.githubusercontent.com/70206832/108716215-97103580-74fa-11eb-8821-eed300f1dcc0.png)
![image](https://user-images.githubusercontent.com/70206832/108716036-5f08f280-74fa-11eb-8271-50e55dfc2e49.png)
Como posso realizar esse save utilizando a biblioteca DataLayer?

**Comment by walissonhms** [comment]
Boa tarde @borges-cincatarina.

está com problema ainda?

**Comment by borges-cincatarina** [comment]
Boa tarde, resolvi da seguinte forma: 
![image](https://user-images.githubusercontent.com/70206832/108744085-47d8fd80-7518-11eb-8e3c-97a8825e7e8a.png)

:D
