### ISSUE TITLE
probema ao salvar multiplos registros (foreach)

### ISSUE THREAD

**Issue by tomsilva** [robsonvleite/datalayer#45]
Boas pessoal, estou tentanto salvar multiplos registros recibos em um json por post. 
eu faco o foreach ele faz passa por todos os objetos do json porem so salva o ultimo registro.

`
   if ($_SERVER['REQUEST_METHOD'] == 'POST'){
	header('Content-type: application/json');
	$headers = json_encode(getallheaders());
    $headers = apache_request_headers();
    $apikey = $headers['Authorization'];
    $token = 'token';
		if (isset($headers['Authorization'])) {
			   
			if ($apikey == $token) {
	
				$ttdd= file_get_contents('php://input');
				$ttdd1 = json_decode($ttdd,true);
				
                foreach($ttdd1["etq"] as $item){
						
                    $lable->EQPID              = ($item["EQPID"]);
                    $lable->UNIDADEID		   = ($item["UNIDADEID"]);
                    $lable->NOM                = ($item["NOM"]);
                    $lable->PRIORIDADEID       = ($item["PRIORIDADEID"]);  
                    $lable->DATAETQ            = ($item["DATAETQ"]);
                    $lable->NOTIFICADORID      = ($item["NOTIFICADORID"]);
                    $lable->MODULOID           = ($item["MODULOID"]);
                    $lable->ANOMALIA           = ($item["ANOMALIA"]);
                    $lable->CAUSAID            = ($item["CAUSAID"]);
                    $lable->CAUSA              = ($item["CAUSA"]);
                    $lable->ACAO               = ($item["ACAO"]);
                    $lable->PESSOAACAO         = ($item["PESSOAACAO"]);
                    $lable->DATAACAO           = ($item["DATAACAO"]);
                    $lable->VALIDADORID        = ($item["VALIDADORID"]);
                    $lable->DATAVALIDACAO      = ($item["DATAVALIDACAO"]);
                    $lable->STATUSID           = ($item["STATUSID"]);
                    $lable->ASSINATURA         = ($item["ASSINATURA"]);
                    $lable->CONTADOR           = ($item["CONTADOR"]);
                    $lable->CLASSIFICACAOID    = ($item["CLASSIFICACAOID"]);
                    $lable->CODIGOEQP          = ($item["CODIGOEQP"]);
                    $lable->USUARIO            = ($item["USUARIO"]);
                    $lable->NOTA               = ($item["NOTA"]);
                    $lable->SISTEMAID          = ($item["SISTEMAID"]);
                   
                     $lable->save();

                    if($lable->fail()){
                        echo $lable->fail()->getMessage();
                        die();
                    }else{
                        var_dump(true);
                    }
				}
			
			}else {
				$msg = 'token invaliddo';
				var_dump($msg);
			}						
		}else {
				$msg = 'Você não tem permissão!';
				var_dump($msg);
		}
}
`

nao sei o que posso estar fazendo de errado 

desde logo obrigado

**Comment by ArianNexux** [comment]
O que acontece é que cada instacia da classe datalayer representa uma linha na respectiva tabela, No seu caso você salva no primeiro ciclo, mas nos restantes ele ao invés de criar um novo registo, simplesmente vai actualizando a mesma linha na tabela, então o resultado final é que é mantido apenas o ultimo registo do array de items na base de dados, A solução no teu caso é dentro do foreach colocar a instância do objecto que vc deseja salvar.
