### ISSUE TITLE
Estava usando a versão 1.1.4 e depois que atualizei deu vários erros.

### ISSUE THREAD

**Issue by MarksEliel** [robsonvleite/datalayer#49]
Gostaria de saber as principais mudanças, da versão 1.1.4 para 1.1.5 por exemplo, pois alguns códigos pararam de funcionar.
Principalmente quando uso fetch, mas não retorna os dados, preciso passar o ->data() antes não precisava, existe algum roteiro das mudanças que precisa ser feitas nos códigos? não encontrei no git.

**Comment by robsonvleite** [comment]
Fala @MarksEliel , você pode comparar as versões aqui no git mesmo: https://github.com/robsonvleite/datalayer/compare/1.1.4...1.1.5

ps. São versões de 2020, de uma para outra mudou apenas o readme, talvez o erro seja outro.
