### ISSUE TITLE
Erro com type da variavel offset

### ISSUE THREAD

**Issue by DesignerDigital** [robsonvleite/datalayer#50]
/** @var int */ protected ?string $limit = null; 
/** @var int */ protected ?int $offset = null;

existe um erro na tipagem da variavel offset do datalayer 2.0.1
se por engano o erro for meu peço aqui minhas desculpas,
porem se puderem me ajudar pois nao consigo usar o paginator por esta questão

**Comment by robsonvleite** [comment]
Obrigado por reportar @DesignerDigital

**Comment by DesignerDigital** [comment]
> Obrigado por reportar @DesignerDigital
Robson estamos com outro poblema em nosso desenvolvimento, no momento em que aplicamos o save() ele persiste no banco porem gera um erro na linha 280 do Datalayer dizendo que o data() é nullo,  fico no aguardo caso nao for um erro gostaria de saber se po nos ajudar a resolver esse problema
