### ISSUE TITLE
 data() on null

### ISSUE THREAD

**Issue by DesignerDigital** [robsonvleite/datalayer#52]
@robsonvleite
Robson estamos com outro poblema em nosso desenvolvimento, no momento em que aplicamos o save() ele persiste no banco porem gera um erro na linha 280 do Datalayer dizendo que o data() é nullo, fico no aguardo caso nao for um erro gostaria de saber se po nos ajudar a resolver esse problema

**Comment by robsonvleite** [comment]
Problema no multi-db meu velho, corrigido na 2.0.5
