### ISSUE TITLE
Fetch retorna null ao utilizar com Firebird

### ISSUE THREAD

**Issue by rafaels86** [robsonvleite/datalayer#62]
Testei o componente com o Firebird nas versões 1.5 e 3.0, e nos dois casos ocorre problema na função fetch, no teste abaixo:
```
if (!$stmt->rowCount()) {
    return null;
}
```
A função sempre entra neste teste e retorna null. Se comentar essa parte do código funciona normalmente.

**Comment by JPirene** [comment]
@robsonvleite Estou com o mesmo problema! Desconfio que até a DSN tenha que ser diferente para poder estabelecer a conexão, e além disso, como manter mais de um Driver ?

**Comment by robsonvleite** [comment]
O problema ocorre mesmo com a consulta trazendo resultados?
